name: Auto Assign
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  auto_assign:
    name: Auto Assign PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: cam3ron2/pr-auto-assign@master
        with:
          reviewers: "MyOrg/some-people,myUsername,someOtherUser"
