name: "PR Auto-assign"
description: "Auto-assign a PR to the author if it is unassigned and request review"
author: "@cam3ron2"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  reviewers:
    description: "comma delimited list of users/teams that will be added as reviewers. team slugs must be prepended with the org they belong to, ex 'MyOrg/Some People' will become MyOrg/some-people"
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run.sh ${{ inputs.reviewers }}
      working-directory: ${{ github.action_path }}
      shell: bash
