name: Tests
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  auto_assign:
    name: Auto Assign PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: cam3ron2/pr-auto-assign@latest
        with:
          reviewers: "cam3ron2"
      - name: Close Pull
        uses: peter-evans/close-pull@v2
        with:
          comment: Auto-closing pull request
          delete-branch: true