name: Release
on:
  pull_request:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Release
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master